server:
  port: 9053
  servlet:
    context-path: /poli/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-35-170-7-252.compute-1.amazonaws.com:5432/d5grh7dihlhohb
    username: roidbgdqttrzsg
    password: 8dd312118e591c41a0236fb45e94ca0e76d6be11ccb437bf9bcf83a27d5385cd
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

